services:
  pgdatabase:
    image: postgres:13
    env_file:
      - my_creds.env
    volumes:
      - dtc_postgres_volume_local:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
volumes:
  dtc_postgres_volume_local:
    external: true